services:
  # MQTT
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    restart: unless-stopped
    ports:
        - "1883:1883"  # MQTT (unsecured)
        - "9001:9001"  # MQTT over WebSockets
    volumes:
        - ./mosquitto/config:/mosquitto/config
        - ./mosquitto/data:/mosquitto/data
        - ./mosquitto/log:/mosquitto/log
  
  # Database
  db:
    image: postgres:16
    container_name: tidc_b205_postgres
    restart: always
    shm_size: 128mb
    volumes:
      - tidc_b205_db:/var/lib/postgresql/data
      - ./local_database/sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${TIMEZONE}
    ports:
      - 5432:5432
  # Database GUI
  adminer:
    image: adminer
    container_name: tidc_b205_adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
  
  # grafana
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_PLUGINS_PREINSTALL=grafana-clock-panel
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER} 
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    ports:
      - "3000:3000"
    volumes:
      - grafana_storage:/var/lib/grafana

volumes:
  tidc_b205_db:
    external: true  # Using exsist volume
    name: postgresql_tidc_b205_db
  grafana_storage:
    external: true
    name: grafana_grafana_storage